spring:
  application:
    name: spring-boot-sqs

aws:
  sqs:
    serviceEndpoint: https://sqs.<ur-region>.amazonaws.com
    signingRegion: <ur-region>
    accessKey: <ur-access-key>
    secretKey: <ur-secret-key>