spring:
  application:
    name: spring-boot-sqs

  cloud:
    aws:
      region:
        static: <ur-region>
      credentials:
        access-key: <ur-access-key>
        secret-key: <ur-secret-key>
      sqs:
        endpoint: <ur-sqs-endpoint-from-aws-console>