
### Get Queues
GET http://localhost:8080/api/v1/queues
Content-Type: application/json

### Get Queues with prefix
GET http://localhost:8080/api/v1/queues/aws
Content-Type: application/json


### Send Messages
POST http://localhost:8080/api/v1/messages/msg
Content-Type: application/json

{
  "message": "Testing the first producer",
  "content": "Welcome to Amazon SQS"
}